### PR TITLE
UserInterface to simplify the User::listing logic

### LINKED ISSUE #42: [DX] User::listing requires ugly logic to make it user-type agnostic
At the time of writing, to be able to ascertain the user ID requires making a specific call to the method of the type of the user you're expecting. If you would run the following piece of code:

```
$userId = User::listing($apiContext)[0]->getUserPerson()->getId();
```

You would run into an exception if the API HTTP response yields a business user (or vice versa when you use `getUserCompany()`:

```
Fatal error: Uncaught Error: Call to a member function getId() on null in /Users/rukn01/Projects/rknol/sdk_php/example/monetary_account_example.php:20
```

So logically speaking if your integration is not aware of the kind of user that will come out of the API, the only way you can express this would be something like this pre-PHP 7.1:

```
$userWrapper = User::listing($apiContext)[0];
$userObj = !is_null($userWrapper->getUserPerson()) 
    ? $userWrapper->getUserPerson() 
    : $userWrapper->getUserCompany();

$userId = $userObj->getId();
```

Or PHP 7.1+ with the null-coalesce operator:

```
$userWrapper = User::listing($apiContext)[0];
$userId = ($userWrapper->getUserPerson() ?? $userWrapper->getUserCompany())->getId();
```

Either scenarios are unfavorable, and unnecessary if the design of the SDK is more developer friendly. I understand that the reasoning behind this is because resource-wise they're 3 different resources, however it makes for very ugly implementation.

One way to solve this would to abstract away the logic inside the `User` resource:

```
class User
{
    // ...
    public function getUserObject()
    {
        return !is_null($this->userPerson)
            ? $this->userPerson
            : $this->userCompany;
    }
}
```

Or something in the likes so that the DX will be:

```
$userId = User::listing($apiContext)[0]->getUserObject()->getId();
```

### PR DESCRIPTION
**Pull request by DennisSnijder**
# Context
#42 

# What has been done
- Added an Interface for all User Objects.
- Added a getter to the User to get a generic user.

# Notes
closes #42

### CODE REVIEW

**Comment by DennisSnijder** [comment]
@dnl-blkv @OGKevin what do you guys think about this approach? Its fairly simple and doesn't have any major impact on the current version.

**Comment by OGKevin** [comment]
@DennisSnijder thanks for this pr.

Unfortunately we can’t merge this because you are changing generated files. To make changes we would need to implement these changes in the generator. If not, any changes implemented outside the generator will be overwritten.

I’m not sure how @dnl-blkv wanted to implement this but nevertheless we will of course take a look at how you did it and see if we can use this as goal once we implement this in the generator.

Because we can’t merge this I’ll close this pr for the sake of overview. But please don’t delete the branch yet so we can come back to view it later.

**Comment by DennisSnijder** [comment]
@OGKevin Where are those models being generated?
Perhaps we can do something there.

**Comment by OGKevin** [comment]
@DennisSnijder Everything in the `Generated` folder is generated code. We have a generator which generates these models. This generator is not open sourced because its hooked to our backend 😉.  So we would have to implement this on our side (in the generator).

If changes are applied to files inside the `Generated` folder that are not from the generator itself, will be overwritten by the generator once we regenerate.

**Pull request closed without merging**
