### PR TITLE
Fix #221 No implicit cast of microtime needed

### LINKED ISSUE #221: SessionContext: "Deprecated: Implicit conversion from float to int loses precision"
## Steps to reproduce:
1. Use PHP 8.1 and catch all errors including deprecations
2. Create a new ApiContext:  `$apiContext = ApiContext::create($environmentType, $apiKey, $appName); `

## What should happen:
1.  Not giving a deprecated message

## What happens:
1. Getting ErrorException with "Deprecated: Implicit conversion from float 1645417887.258314 to int loses precision"

## Traceback
Relevant traceback entry (from my sentry setup):
> Crashed in non-app: /vendor/bunq/sdk_php/src/Context/SessionContext.php in bunq\Context\SessionContext::microTimeToDateTime

## SDK version and environment
- Tested on 1.19.1
- PHP 8.1.2 (Docker setup from php:8.1-fpm-buster)
- If relevant: Symfony 5.4.4
- [ ] Sandbox
- [x] Production

## Extra info:
The implicit conversion of float to int which leads to a loss in precision is deprecated since PHP 8.1.

`float $microtime` is passed thru as second parameter to `date()`, but that must be an `int` so it is cast implicit here: https://github.com/bunq/sdk_php/blob/dbe2472580051db7ada486406450f0b30ad99221/src/Context/SessionContext.php#L134

### PR DESCRIPTION
**Pull request by erkens**
This fix will make sure the implicit cast of microtime is not done anymore, because it has been done in a new variable, which also means that the "cast" is only done once, because it was already needed for the `floor()`-function.

It should work on all supported PHP versions, but I only tested it with 8.1

 - Closes bunq/sdk_php#221
    - [x] Tested

### CODE REVIEW

**Comment by erkens** [comment]
Is bunq maintaining their API? Please merge this or give at least a reaction why you won't include this...

**Comment by StanJansen** [comment]
Hi @sailingdeveloper , sorry for tagging, but I noticed you picked up the last PR that got merged.

This issue causes the SDK to no longer work for us, and we'd prefer not having to create a fork. Could this be looked at / merged, or if a new PR needs to be made as this one is quite old i'd be happy to do that.

We temporarily created a fork with the following change in `src/Context/SessionContext.php`:

- Replaced `return static::microTimeToDateTime($expiryTime);` with `return DateTime::createFromFormat('U.u', $expiryTime);`
- Removed `private static function microTimeToDateTime` as a whole

If this SDK will no longer be maintained we'd also like to know it so we can look for alternatives.

**Review by sailingdeveloper — APPROVED** [review]

**Comment by sailingdeveloper** [comment]
@StanJansen Merged for now, but this will be reverted as soon as the next backend version is released, which happens often 😅 

I’ll take a look if we can fix this structurally 🙏

**Comment by StanJansen** [comment]
> @StanJansen Merged for now, but this will be reverted as soon as the next backend version is released, which happens often 😅
> 
> I’ll take a look if we can fix this structurally 🙏

Thanks for the quick reply! That would be great :pray:

**Pull request merged**
